"""
FastAPI service for Amazon Review Sentiment prediction.

How to run
----------
From the project root:
    uvicorn api.main:app --reload --port 8000

Endpoints
---------
GET  /          → health check
POST /predict   → returns predicted sentiment

Interactive docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""

from pathlib import Path

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from src.predict import Predictor

# ---------------------------------------------------------------------------
# Artefact loading (happens once at server startup)
# ---------------------------------------------------------------------------
MODEL_DIR = Path(__file__).parent.parent / 'models'

try:
    predictor = Predictor(MODEL_DIR)
except FileNotFoundError as exc:
    raise RuntimeError(
        f"Model artefacts not found in {MODEL_DIR}. "
        "Run the training notebook first to generate best_model.joblib, "
        "tfidf_vectorizer.joblib, and label_encoder.joblib."
    ) from exc

# ---------------------------------------------------------------------------
# App definition
# ---------------------------------------------------------------------------
app = FastAPI(
    title='Amazon Review Sentiment API',
    description=(
        'Predicts whether an Amazon product review is '
        'positive, neutral, or negative.'
    ),
    version='1.0.0',
)


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------
class ReviewRequest(BaseModel):
    review_text: str
    review_score: float = 3.0   # star rating 1–5; defaults to 3 if unknown

    model_config = {
        'json_schema_extra': {
            'examples': [{
                'review_text': 'Great product, works exactly as described!',
                'review_score': 5.0,
            }]
        }
    }


class SentimentResponse(BaseModel):
    review_text: str
    sentiment: str          # 'positive' | 'neutral' | 'negative'
    review_score: float


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.get('/')
def root():
    return {'status': 'ok', 'message': 'Amazon Review Sentiment API is running.'}


@app.post('/predict', response_model=SentimentResponse)
def predict_sentiment(request: ReviewRequest):
    if not request.review_text.strip():
        raise HTTPException(status_code=422, detail='review_text cannot be empty.')

    sentiment = predictor.predict(request.review_text, request.review_score)

    return SentimentResponse(
        review_text=request.review_text,
        sentiment=sentiment,
        review_score=request.review_score,
    )
